Traceback (most recent call last):
  File "/Users/kvarada/opt/miniconda3/envs/571/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/kvarada/opt/miniconda3/envs/571/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kvarada/opt/miniconda3/envs/571/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kvarada/opt/miniconda3/envs/571/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kvarada/opt/miniconda3/envs/571/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kvarada/opt/miniconda3/envs/571/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Users/kvarada/opt/miniconda3/envs/571/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/kvarada/opt/miniconda3/envs/571/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sys

import IPython
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import HTML

sys.path.append("code/.")

import ipywidgets as widgets
import mglearn
from IPython.display import display
from ipywidgets import interact, interactive
from plotting_functions import *
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import cross_validate, train_test_split
from utils import *

%matplotlib inline

pd.set_option("display.max_colwidth", 200)
import warnings

warnings.filterwarnings("ignore")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/80/kr9rkqfj4w78h49djkz8yy9r0000gp/T/ipykernel_11689/73640380.py[0m in [0;36m<module>[0;34m[0m
[1;32m     13[0m [0;32mfrom[0m [0mIPython[0m[0;34m.[0m[0mdisplay[0m [0;32mimport[0m [0mdisplay[0m[0;34m[0m[0;34m[0m[0m
[1;32m     14[0m [0;32mfrom[0m [0mipywidgets[0m [0;32mimport[0m [0minteract[0m[0;34m,[0m [0minteractive[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 15[0;31m [0;32mfrom[0m [0mplotting_functions[0m [0;32mimport[0m [0;34m*[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     16[0m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mdummy[0m [0;32mimport[0m [0mDummyClassifier[0m[0;34m[0m[0;34m[0m[0m
[1;32m     17[0m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mmodel_selection[0m [0;32mimport[0m [0mcross_validate[0m[0;34m,[0m [0mtrain_test_split[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/CS/2021-22/330/cpsc330/lectures/code/./plotting_functions.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0mutils[0m [0;32mimport[0m [0;34m*[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mimport[0m [0mmglearn[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mfrom[0m [0mimageio[0m [0;32mimport[0m [0mimread[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mneighbors[0m [0;32mimport[0m [0mKNeighborsClassifier[0m[0;34m,[0m [0mKNeighborsRegressor[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/CS/2021-22/330/cpsc330/lectures/code/./utils.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;32mimport[0m [0mre[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mfrom[0m [0mPIL[0m [0;32mimport[0m [0mImage[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0;32mfrom[0m [0mtorchvision[0m[0;34m.[0m[0mmodels[0m [0;32mimport[0m [0mvgg16[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0;32mfrom[0m [0mtorchvision[0m [0;32mimport[0m [0mtransforms[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;32mimport[0m [0mtorch[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/miniconda3/envs/cpsc330/lib/python3.9/site-packages/torchvision/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;32mimport[0m [0mos[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mfrom[0m [0;34m.[0m[0mextension[0m [0;32mimport[0m [0m_HAS_OPS[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0;32mfrom[0m [0mtorchvision[0m [0;32mimport[0m [0mmodels[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/miniconda3/envs/cpsc330/lib/python3.9/site-packages/torchvision/extension.py[0m in [0;36m<module>[0;34m[0m
[1;32m     49[0m [0;34m[0m[0m
[1;32m     50[0m [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 51[0;31m     [0m_register_extensions[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     52[0m     [0m_HAS_OPS[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m
[1;32m     53[0m [0;34m[0m[0m

[0;32m~/opt/miniconda3/envs/cpsc330/lib/python3.9/site-packages/torchvision/extension.py[0m in [0;36m_register_extensions[0;34m()[0m
[1;32m     45[0m     [0;32mif[0m [0mext_specs[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     46[0m         [0;32mraise[0m [0mImportError[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 47[0;31m     [0mtorch[0m[0;34m.[0m[0mops[0m[0;34m.[0m[0mload_library[0m[0;34m([0m[0mext_specs[0m[0;34m.[0m[0morigin[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     48[0m [0;34m[0m[0m
[1;32m     49[0m [0;34m[0m[0m

[0;31mAttributeError[0m: module 'torch' has no attribute 'ops'
AttributeError: module 'torch' has no attribute 'ops'

