Traceback (most recent call last):
  File "/Users/kvarada/opt/miniconda3/envs/cpsc330/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/kvarada/opt/miniconda3/envs/cpsc330/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kvarada/opt/miniconda3/envs/cpsc330/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kvarada/opt/miniconda3/envs/cpsc330/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kvarada/opt/miniconda3/envs/cpsc330/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kvarada/opt/miniconda3/envs/cpsc330/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Users/kvarada/opt/miniconda3/envs/cpsc330/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/kvarada/opt/miniconda3/envs/cpsc330/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
assert np.allclose(
    my_dc.predict_proba(X_train_dummy), sk_dc.predict_proba(X_train_dummy)
)
assert np.allclose(
    my_dc.predict_proba(X_valid_dummy), sk_dc.predict_proba(X_valid_dummy)
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
[0;32m/var/folders/80/kr9rkqfj4w78h49djkz8yy9r0000gp/T/ipykernel_5624/3894093271.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m assert np.allclose(
[0m[1;32m      2[0m     [0mmy_dc[0m[0;34m.[0m[0mpredict_proba[0m[0;34m([0m[0mX_train_dummy[0m[0;34m)[0m[0;34m,[0m [0msk_dc[0m[0;34m.[0m[0mpredict_proba[0m[0;34m([0m[0mX_train_dummy[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m )
[1;32m      4[0m assert np.allclose(
[1;32m      5[0m     [0mmy_dc[0m[0;34m.[0m[0mpredict_proba[0m[0;34m([0m[0mX_valid_dummy[0m[0;34m)[0m[0;34m,[0m [0msk_dc[0m[0;34m.[0m[0mpredict_proba[0m[0;34m([0m[0mX_valid_dummy[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAssertionError[0m: 
AssertionError: 

